
CREATE TABLE IF NOT EXISTS plvr_land_moi_gov_tw (
  serial_number TEXT,
  city TEXT,
  district TEXT,
  transaction_type TEXT,
  address TEXT,
  land_shifting_area_sqm DECIMAL(10,4),
  urban_land_use TEXT,
  non_urban_land_use TEXT,
  non_urban_land_designation TEXT,
  transaction_date DATE,
  transaction_pen_number TEXT,
  floor TEXT,
  total_floor TEXT,
  building_type TEXT,
  primary_use TEXT,
  primary_material TEXT,
  construction_complete_date DATE,
  building_area_sqm DECIMAL(10,4),
  number_of_rooms TEXT,
  number_of_living_rooms INTEGER,
  number_of_bathrooms INTEGER,
  partitioned TEXT,
  has_management_organization TEXT,
  total_price INTEGER,
  unit_price_per_sqm INTEGER,
  parking_type TEXT,
  parking_area_sqm DECIMAL(10,4),
  parking_price INTEGER,
  notes TEXT,
  main_building_area_sqm DECIMAL(10,4),
  subsidiary_building_area_sqm DECIMAL(10,4),
  balcony_area_sqm DECIMAL(10,4),
  elevator TEXT,
  transaction_identifier TEXT
);
